/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    String eresMayor(int edad) {
        return (edad >= 18) ? "Eres mayor" : "Eres menor, le gustas a jordi";
    }

    void loop(/* Parametros */) {
        jordi:for (int i = 1; i < 10; i++) {
            for (int j = 1; j < 4; j++) {
                if (j == 2) break jordi;
                System.out.println(i + ", " + j);
            }
        }
    }

    public static void main(String[] args) {
        App func = new App();

        func.loop();
    }
}
