/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class AppTest {

    App classToTest = new App();

    @Test
    void testArrays() {
        int[] nums = { 10, 8, 9, 10, 8 };

        int want = 9;
        int got = classToTest.getAverage(nums);

        assertEquals(
            want,
            got,
            "Error. La suma no se esta realizando correctamente"
        );
    }

    @Test
    void testEvens() {
        int[] nums = { 10, 3, 1, 10, 11 };

        int want = 2;
        int got = classToTest.getEvens(nums);

        assertEquals(
            want,
            got,
            "Error. La suma no se esta realizando correctamente"
        );
    }

    @Test
    void testGreater() {
        int[] nums = { 10, 1, 2, 100, 11 };

        int want = 100;
        int got = classToTest.getGreater(nums);

        assertEquals(
            want,
            got,
            "Error. La suma no se esta realizando correctamente"
        );
    }

    @Test
    void testLower() {
        int[] nums = { 10, 1, 2, 100, 11 };

        int want = 1;
        int got = classToTest.getLower(nums);

        assertEquals(
            want,
            got,
            "Error. La suma no se esta realizando correctamente"
        );
    }
}
