/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayInputStream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class AppTest {

    App classUnderTest = new App();

    @Test
    @DisplayName("Test BMI")
    void bmiFormula() {
        ByteArrayInputStream weight = new ByteArrayInputStream(
            Double.toString(70.0).getBytes()
        );

        ByteArrayInputStream height = new ByteArrayInputStream(
            Double.toString(1.8).getBytes()
        );

        String want = "Normaear";
        String got = classUnderTest.getBmi(height, weight);
        assertEquals(
            want,
            got,
            "Error. hay algo mal en la formula se recibio: " +
            got +
            ". Queriamos " +
            want
        );
    }
}
