/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.InputStream;
import java.util.Scanner;

public class App {

    private double height;
    private double weight;

    String getBmi(InputStream height_input, InputStream weight_input) {
        Scanner height_reader = new Scanner(height_input);
        Scanner weight_reader = new Scanner(weight_input);

        this.height = height_reader.nextFloat();
        this.weight = weight_reader.nextFloat();

        height_reader.close();
        weight_reader.close();

        double bmi = this.weight / (Math.pow(this.height, 2));

        if (bmi < 18.5) {
            return "Bajo peso";
        } else if (bmi < 25) {
            return "Normal";
        } else if (bmi < 30) {
            return "Sobrepeso";
        } else {
            return "Obeso";
        }
    }
}
