/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;

class App {

    int getAverage(int[] nums) {
        return 0;
    }

    int getEvens(int[] nums) {
        return 0;
    }

    int getGreater(int[] nums) {
        return 0;
    }

    int getLower(int[] nums) {
        return 0;
    }
}
