/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayInputStream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class AppTest {

    class GetNum implements TimeInMillis {

        public long currentTimeMillis() {
            return 2;
        }
    }

    App classToTest = new App(new GetNum(), new GetNum());

    @Test
    @DisplayName("Test")
    void getAnswerTest() {
        ByteArrayInputStream inputStream = new ByteArrayInputStream(
            Integer.toString(4).getBytes()
        );

        // Redirigimos System.in a nuestro InputStream simulado
        System.setIn(inputStream);

        String got = classToTest.getAnswer();
        String want = "Le atinaste a la suma!";

        assertEquals(want, got, "Suma erronea");
    }
}
